name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: achaykovsky/.github/.github/workflows/python-ci.yml@main
    with:
      python-version: "3.11"
      pytest-args: '-m "not integration"'
